10:23:01:  = Creation of this file = 

10:23:01: Date 15/10/2021 already added (date ID: 18)
10:23:17: HTTPConnectionPool(host='firefox-webdriver', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef6781bb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
10:23:17: The connection to remote webdriver failed. Check if the container is running.
10:23:17: If it is, check the hostname in globals.py and other connection settings.

