10:20:58:  = Creation of this file = 

10:20:58: Date 15/10/2021 already added (date ID: 18)
10:21:14: HTTPConnectionPool(host='firefox-webdriver', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd04ff5a8f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
10:21:14: The connection to remote webdriver failed. Check if the container is running.
10:21:14: If it is, check the hostname in etl/globals.py and other configuration settings.

